version: 2
jobs:
  extract-codelists:
    docker:
      - image: bertvannuffelen/codelist-aggregator
    steps:
      - checkout
      - run: mkdir -p workspace
      - run:
          name: aggregate-codelists
          command: |
            /scripts/aggregatecodelist.sh codelijsten
      - run:
          name: List the files which have been created
          command: ls -al /tmp/workspace/*
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/
  create-artifact:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "50:6e:4e:a8:f0:bf:47:7d:65:a9:90:38:ab:9a:c9:f4"
      - run:
          name: Checkout target repo
          workdir: /tmp
          command: |
            rm -rf codelist-generated
            git clone git@github.com:Informatievlaanderen/OSLO-codelistgenerated.git
      - run:
          name: Switch to the target directory
          workdir: /tmp/OSLO-codelistgenerated
          command: |
            git fetch origin
            git checkout -b "grb-${CIRCLE_BRANCH}" --track "origin/grb-${CIRCLE_BRANCH}"
      - run:
          name: Copy assets
          workdir: /tmp/workspace
          command: |
            cp -R target/all.nt.gz /tmp/OSLO-codelistgenerated/
            gunzip -f /tmp/OSLO-codelistgenerated/all.nt.gz
            cp -R target/all.ttl /tmp/OSLO-codelistgenerated/
      - run:
          name: Push results to github
          workdir: /tmp/OSLO-codelistgenerated
          command: |
            git config user.email "circleci@data.vlaanderen.be"
            git config user.name "Circle CI Builder"
            git add .
            git commit -m "Applying changes from commit ${CIRCLE_SHA1}" --allow-empty
            git push origin "grb-${CIRCLE_BRANCH}"
workflows:
  version: 2
  generate_documentation:
    jobs:
      - extract-codelists
      - create-artifact:
          requires:
            - extract-codelists
